# Generated by Django 2.0.2 on 2018-03-28 19:01

import adock.transporteurs.validators
import django.contrib.postgres.fields
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transporteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siret', models.CharField(db_index=True, editable=False, max_length=14, unique=True, validators=[adock.transporteurs.validators.validate_siret])),
                ('raison_sociale', models.CharField(max_length=131)),
                ('categorie_juridique', models.TextField()),
                ('is_siege', models.BooleanField(default=False)),
                ('adresse', models.CharField(max_length=126)),
                ('code_postal', models.CharField(max_length=5)),
                ('ville', models.CharField(max_length=32)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('date_creation', models.DateField()),
                ('debut_activite', models.DateField()),
                ('code_ape', models.CharField(max_length=5)),
                ('libelle_ape', models.CharField(max_length=65)),
                ('gestionnaire', models.CharField(max_length=131)),
                ('lti_numero', models.CharField(blank=True, default='', max_length=16)),
                ('lti_date_debut', models.DateField(blank=True, null=True)),
                ('lti_date_fin', models.DateField(blank=True, null=True)),
                ('lti_nombre', models.PositiveSmallIntegerField(default=0)),
                ('lc_numero', models.CharField(blank=True, default='', max_length=16)),
                ('lc_date_debut', models.DateField(blank=True, null=True)),
                ('lc_date_fin', models.DateField(blank=True, null=True)),
                ('lc_nombre', models.PositiveSmallIntegerField(default=0)),
                ('numero_tva', models.CharField(max_length=13)),
                ('working_area', models.CharField(blank=True, choices=[('', 'Non définie'), ('FRANCE', 'France'), ('DEPARTEMENT', 'Départementale')], default='', max_length=12)),
                ('working_area_departements', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('completeness', models.PositiveSmallIntegerField(default=40)),
            ],
            options={
                'db_table': 'transporteur',
            },
        ),
    ]
