# Generated by Django 2.0.2 on 2018-03-13 12:06

import adock.transporteurs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transporteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siret', models.CharField(db_index=True, editable=False, max_length=14, unique=True)),
                ('siren', models.CharField(db_index=True, editable=False, max_length=9, validators=[adock.transporteurs.validators.validate_siren])),
                ('nic', models.CharField(editable=False, max_length=5, validators=[adock.transporteurs.validators.validate_nic])),
                ('raison_sociale', models.CharField(max_length=38)),
                ('adresse', models.TextField()),
                ('code_postal', models.CharField(max_length=5)),
                ('telephone', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_creation', models.DateField()),
                ('debut_activite', models.DateField()),
                ('code_ape', models.CharField(max_length=5)),
                ('libelle_ape', models.CharField(max_length=65)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
