# Generated by Django 2.0.6 on 2018-06-27 18:54

import adock.transporteurs.validators
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transporteur',
            fields=[
                ('siret', models.CharField(db_index=True, editable=False, max_length=14, primary_key=True, serialize=False)),
                ('raison_sociale', models.CharField(max_length=131)),
                ('enseigne', models.CharField(max_length=131)),
                ('categorie_juridique', models.TextField()),
                ('is_siege', models.BooleanField(default=False)),
                ('adresse', models.CharField(max_length=126)),
                ('code_postal', models.CharField(max_length=5)),
                ('ville', models.CharField(max_length=32)),
                ('departement', models.CharField(blank=True, default='', max_length=3)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('date_creation', models.DateField(blank=True, null=True)),
                ('debut_activite', models.DateField(blank=True, null=True)),
                ('code_ape', models.CharField(max_length=5)),
                ('libelle_ape', models.CharField(max_length=65)),
                ('gestionnaire', models.CharField(max_length=131)),
                ('lti_numero', models.CharField(blank=True, default='', max_length=16)),
                ('lti_date_debut', models.DateField(blank=True, null=True)),
                ('lti_date_fin', models.DateField(blank=True, null=True)),
                ('lti_nombre', models.PositiveSmallIntegerField(default=0)),
                ('lc_numero', models.CharField(blank=True, default='', max_length=16)),
                ('lc_date_debut', models.DateField(blank=True, null=True)),
                ('lc_date_fin', models.DateField(blank=True, null=True)),
                ('lc_nombre', models.PositiveSmallIntegerField(default=0)),
                ('numero_tva', models.CharField(blank=True, max_length=13, null=True)),
                ('working_area', models.CharField(blank=True, choices=[('', 'Non définie'), ('INTERNATIONAL', 'Internationale'), ('FRANCE', 'France'), ('DEPARTEMENT', 'Départementale')], default='', max_length=15)),
                ('working_area_departements', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), blank=True, null=True, size=None, validators=[adock.transporteurs.validators.validate_french_departement])),
                ('specialities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('LOT', 'Transport de lots'), ('PALETTE', 'Palettes / Messagerie palettisée'), ('URBAIN', 'Urbain / Dernier kilomètre'), ('VRAC_SOLIDE', 'Vrac solide'), ('VRAC_LIQUIDE', 'Vrac liquide'), ('TEMPERATURE', 'Température dirigée'), ('PLATEAU', 'Plateau bachés et spécifiques'), ('MULTIMODAL', 'Multimodal'), ('LOCATION', 'Location'), ('ANIMAL', 'Animaux vivants'), ('VEHICULE', 'Transport de véhicules'), ('AUTRE', 'Autre')], max_length=63), blank=True, null=True, size=None)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('completeness', models.PositiveSmallIntegerField(default=40)),
                ('in_sirene', models.BooleanField(default=False, help_text="Drapeau indiquant la présence de l'entreprise dans la base de données Sirene.")),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transporteur',
            },
        ),
        migrations.CreateModel(
            name='TransporteurFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=126)),
                ('url', models.URLField()),
                ('filename', models.FilePathField(path='/Users/sra/webstack/src/adock-api/datafiles')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transporteur_feed',
            },
        ),
        migrations.CreateModel(
            name='TransporteurLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('transporteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporteurs.Transporteur')),
            ],
            options={
                'db_table': 'transporteur_log',
            },
        ),
        migrations.AddIndex(
            model_name='transporteur',
            index=models.Index(fields=['enseigne', '-completeness'], name='transporteur_search_order_by'),
        ),
    ]
