# Generated by Django 2.0.2 on 2018-03-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporteurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporteur',
            name='adresse',
            field=models.CharField(max_length=126),
        ),
        migrations.AlterField(
            model_name='transporteur',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='transporteur',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=63),
        ),
    ]
