# Generated by Django 2.0.6 on 2018-06-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("transporteurs", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="transporteur",
            name="email_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        )
    ]
