# Generated by Django 2.0.4 on 2018-04-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporteurs', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transporteur',
            index=models.Index(fields=['raison_sociale', '-completeness'], name='transporteur_search_order_by'),
        ),
    ]
