# Generated by Django 2.0.4 on 2018-04-04 08:56
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transporteurs', '0002_auto_20180404_0835'),
    ]

    operations = [
        TrigramExtension()
    ]
