# Generated by Django 2.0.2 on 2018-03-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporteurs', '0003_auto_20180313_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporteur',
            name='greater_than_35t_licenses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transporteur',
            name='lower_than_35t_licenses',
            field=models.IntegerField(default=0),
        ),
    ]
