# Generated by Django 2.0.4 on 2018-04-04 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transporteurs', '0003_extension_pg_trgm'),
    ]

    operations = [
        # GinIndex of Django can't be used here
        migrations.RunSQL(
            'CREATE INDEX transporteur_search_trgm ON transporteur USING GIN (raison_sociale GIN_TRGM_OPS);'
        ),
    ]
