# Generated by Django 2.0.6 on 2018-07-05 13:47

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("transporteurs", "0003_auto_20180704_0913")]

    operations = [TrigramExtension()]
