# Generated by Django 2.0.4 on 2018-04-04 10:32

from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transporteurs', '0004_auto_20180404_0932'),
    ]

    operations = [
        HStoreExtension(),
    ]
