# Generated by Django 2.0.4 on 2018-04-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporteurs', '0005_extension_hstore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporteur',
            name='id',
        ),
        migrations.AlterField(
            model_name='transporteur',
            name='siret',
            field=models.CharField(db_index=True, editable=False, max_length=14, primary_key=True, serialize=False),
        ),
    ]
