# Generated by Django 2.0.6 on 2018-07-05 13:55

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [("transporteurs", "0005_search_trgm_enseigne")]

    operations = [UnaccentExtension()]
