# Generated by Django 2.0.2 on 2018-03-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporteurs', '0005_auto_20180313_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporteur',
            name='ville',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transporteur',
            name='raison_sociale',
            field=models.CharField(max_length=131),
        ),
    ]
