# Generated by Django 2.0.2 on 2018-03-16 21:09

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('transporteurs', '0006_auto_20180314_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporteur',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
        ),
    ]
