# Generated by Django 2.0.4 on 2018-04-04 11:07

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transporteurs', '0006_auto_20180404_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransporteurLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', django.contrib.postgres.fields.hstore.HStoreField()),
                ('transporteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporteurs.Transporteur')),
            ],
            options={
                'db_table': 'transporteur_log',
            },
        ),
    ]
