# Generated by Django 2.0.4 on 2018-04-09 15:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transporteurs', '0007_transporteurlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporteurlog',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
