# Generated by Django 2.0.6 on 2018-07-09 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transporteurs', '0007_transporteur_enseigne_unaccent'),
    ]

    operations = [
        migrations.RunSQL("UPDATE transporteur SET enseigne_unaccent = UNACCENT(enseigne);")
    ]
