# Generated by Django 2.0.2 on 2018-03-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporteurs', '0007_auto_20180316_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporteur',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
