# Generated by Django 2.0.2 on 2018-03-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporteurs', '0008_transporteur_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporteur',
            name='numero_tva',
            field=models.CharField(default='', max_length=13),
            preserve_default=False,
        ),
    ]
