# Generated by Django 2.0.6 on 2018-07-09 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transporteurs', '0008_populate_enseigne_unaccent'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS transporteur_search_trgm_enseigne_unaccent ON transporteur USING GIN (enseigne_unaccent GIN_TRGM_OPS);"
        )
    ]
