# Generated by Django 2.0.4 on 2018-04-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporteurs', '0009_drop_hstore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporteur',
            name='date_creation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transporteur',
            name='debut_activite',
            field=models.DateField(blank=True, null=True),
        ),
    ]
