# Generated by Django 2.0.6 on 2018-07-10 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transporteurs', '0009_index_enseigne_unaccent'),
    ]

    operations = [
        migrations.RunSQL('DROP INDEX transporteur_search_trgm_enseigne;')
    ]
