# Generated by Django 2.0.2 on 2018-03-21 17:36

from django.db import connection
from django.db import migrations

def set_vat_number(apps, schema_editor):
    with connection.cursor() as cursor:
        # Query pasted from from transporteur-merge.sql
        cursor.execute("""
            update transporteurs_transporteur
               set numero_tva = 'FR' || to_char((12 + 3 * (cast(siret::char(9) as bigint) % 97)) % 97, 'fm00') || siret::char(9)
            """)

class Migration(migrations.Migration):

    dependencies = [
        ('transporteurs', '0009_transporteur_numero_tva'),
    ]

    operations = [
        migrations.RunPython(set_vat_number),
    ]
