# Generated by Django 2.0.2 on 2018-03-21 17:36

from django.db import migrations

query = """
    UPDATE transporteurs_transporteur
       SET numero_tva = 'FR' || TO_CHAR((12 + 3 * (CAST(siret::CHAR(9) as bigint) % 97)) % 97, 'fm00') || siret::CHAR(9)
"""

class Migration(migrations.Migration):

    dependencies = [
        ('transporteurs', '0009_transporteur_numero_tva'),
    ]

    operations = [
        migrations.RunSQL(query),
    ]
