# Generated by Django 2.0.4 on 2018-04-10 15:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporteurs', '0010_auto_20180410_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporteur',
            name='specialities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('LOT', 'Transport de lots'), ('PALETTE', 'Palettes / Messagerie palettisée'), ('URBAIN', 'Urbain / Dernier kilomètre'), ('VRAC_SOLIDE', 'Vrac solide'), ('VRAC_LIQUIDE', 'Vrac liquide'), ('TEMPERATURE', 'Temérature dirigée'), ('PLATEAU', 'Plateau bachés et spécifiques'), ('MULTIMODAL', 'Multimodal'), ('LOCATION', 'Location'), ('ANIMAL', 'Animaux vivants'), ('VEHICULE', 'Transport de véhicules')], max_length=63), blank=True, null=True, size=None),
        ),
    ]
