# Generated by Django 2.0.2 on 2018-03-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporteurs', '0010_auto_20180321_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transporteur',
            old_name='updated_at',
            new_name='validated_at',
        )
    ]
