# Generated by Django 2.1 on 2018-08-09 13:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporteurs', '0011_auto_20180710_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporteur',
            name='specialities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('LOT', 'Transport de lots'), ('PALETTE', 'Palettes / Messagerie palettisée'), ('URBAIN', 'Urbain / Dernier kilomètre'), ('VRAC_SOLIDE', 'Vrac solide'), ('VRAC_LIQUIDE', 'Vrac liquide'), ('TEMPERATURE', 'Température dirigée'), ('PLATEAU', 'Plateau bachés et spécifiques'), ('MESSAGERIE', 'Messagerie express'), ('MULTIMODAL', 'Multimodal'), ('LOCATION', 'Location'), ('ANIMAL', 'Animaux vivants'), ('VEHICULE', 'Transport de véhicules'), ('AUTRE', 'Autre')], max_length=63), blank=True, null=True, size=None),
        ),
    ]
