# Generated by Django 2.0.2 on 2018-03-21 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporteurs', '0011_auto_20180321_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporteur',
            name='completeness',
            field=models.IntegerField(default=40),
        ),
    ]
