# Generated by Django 2.0.2 on 2018-03-21 22:59

from django.db import migrations

def compute_completeness(apps, schema_editor):
    Transporteur = apps.get_model('transporteurs', 'Transporteur')

    # It's not possible to depend on application in a migration...
    for transporteur in Transporteur.objects.all():  # pragma: no cover
        earned_points = 0
        if transporteur.telephone:
            earned_points += 1
        if transporteur.email:
            earned_points += 1
        transporteur.completeness = 40 + 15 * earned_points
        # It doesn't call our custom model save()
        transporteur.save()

class Migration(migrations.Migration):

    dependencies = [
        ('transporteurs', '0012_transporteur_completeness'),
    ]

    operations = [
        migrations.RunPython(compute_completeness, atomic=True)
    ]
