# Generated by Django 2.0.4 on 2018-04-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporteurs', '0012_auto_20180417_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporteur',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
