# Generated by Django 2.0.4 on 2018-05-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporteurs', '0013_transporteur_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporteur',
            name='working_area',
            field=models.CharField(blank=True, choices=[('', 'Non définie'), ('INTERNATIONAL', 'Internationale'), ('FRANCE', 'France'), ('DEPARTEMENT', 'Départementale')], default='', max_length=15),
        ),
    ]
