# Generated by Django 2.0.2 on 2018-03-26 09:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporteurs', '0013_auto_20180321_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporteur',
            name='working_area',
            field=models.CharField(
                choices=[('', 'Non définie'), ('FRANCE', 'France'), ('DEPARTEMENT', 'Départementale')],
                default='', max_length=12
            )
        ),
        migrations.AddField(
            model_name='transporteur',
            name='working_area_departements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
