# Generated by Django 2.1 on 2018-08-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("transporteurs", "0013_better_working_area_departements")]

    operations = [
        migrations.AddField(
            model_name="transporteur",
            name="objectif_co2",
            field=models.CharField(
                blank=True,
                choices=[("ENLISTED", "Engagé"), ("LABELLED", "Labellisé")],
                default="",
                max_length=8,
            ),
        )
    ]
