# Generated by Django 2.0.4 on 2018-05-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporteurs', '0014_auto_20180503_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransporteurScraper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=126)),
                ('url', models.URLField()),
            ],
            options={
                'db_table': 'transporteur_scraper',
            },
        ),
    ]
