# Generated by Django 2.0.4 on 2018-05-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporteurs', '0015_transporteurfeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporteurfeed',
            name='is_applied',
            field=models.BooleanField(default=False),
        ),
    ]
