# Generated by Django 2.0.4 on 2018-05-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporteurs', '0016_transporteurscraper_is_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporteur',
            name='in_sirene',
            field=models.BooleanField(default=False, help_text="Drapeau indiquant la présence de l'entreprise dans la base de données Sirène."),
        ),
    ]
