# Generated by Django 2.1 on 2018-09-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("transporteurs", "0017_auto_20180913_2219")]

    operations = [
        migrations.AlterField(
            model_name="transporteur",
            name="working_area",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Non définie"),
                    ("INTERNATIONAL", "Internationale"),
                    ("FRANCE", "France"),
                    ("REGION", "Régionale"),
                    ("DEPARTEMENT", "Départementale"),
                ],
                default="",
                max_length=15,
            ),
        )
    ]
