# Generated by Django 2.0.4 on 2018-05-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporteurs', '0018_auto_20180531_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporteurfeed',
            name='filename',
            field=models.FilePathField(default='', path='/Users/sra/webstack/src/adock-api/datafiles'),
            preserve_default=False,
        ),
    ]
