# Generated by Django 2.1.2 on 2018-10-15 15:53
import ast

from django.db import migrations


def fix_transporteur_log_json(apps, _schema_editor):
    TransporteurLog = apps.get_model('transporteurs', 'TransporteurLog')
    for transporteur_log in TransporteurLog.objects.all():
        cleaned_data = {}
        for k, v in transporteur_log.data.items():
            if v != '' and v[0] == '[':
                v = ast.literal_eval(v)
            elif v == 'None':
                v = []

            cleaned_data[k] = v

        transporteur_log.data = cleaned_data
        transporteur_log.save()

class Migration(migrations.Migration):

    dependencies = [
        ('transporteurs', '0019_auto_20181005_1610'),
    ]

    operations = [
        migrations.RunPython(fix_transporteur_log_json)
    ]
