# Generated by Django 2.0.4 on 2018-06-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporteurs', '0019_transporteurfeed_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporteur',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
