# Generated by Django 2.0.4 on 2018-06-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporteurs', '0020_transporteur_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporteur',
            name='numero_tva',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
