# Generated by Django 2.0.4 on 2018-06-07 14:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporteurs', '0021_auto_20180603_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporteur',
            name='working_area_departements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), blank=True, null=True, size=None),
        ),
    ]
