# Generated by Django 2.0.4 on 2018-06-11 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transporteurs', '0022_auto_20180607_1453'),
    ]

    operations = [
        # Transporteur not in Sirène won't have a default departement set
        migrations.RunSQL(
            """update transporteur t
                  set working_area_departements = array[s.depet]
                 from sirene s
                where t.siret = s.siret
                  and (t.working_area_departements = array['20']::varchar(3)[]
                       or t.working_area_departements = array[]::varchar(3)[]);
            """
        )
    ]
