# Generated by Django 2.0.4 on 2018-06-14 10:25

import adock.transporteurs.validators
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporteurs', '0022_auto_20180607_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporteur',
            name='departement',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='transporteur',
            name='working_area_departements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), blank=True, null=True, size=None, validators=[adock.transporteurs.validators.validate_french_departement]),
        ),
    ]
