# Generated by Django 2.0.6 on 2018-06-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporteurs', '0023_auto_20180614_1025'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transporteur',
            name='transporteur_search_order_by',
        ),
        migrations.AddField(
            model_name='transporteur',
            name='enseigne',
            field=models.CharField(default='', max_length=131),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='transporteur',
            index=models.Index(fields=['enseigne', '-completeness'], name='transporteur_search_order_by'),
        ),
    ]
