# Generated by Django 2.0.6 on 2018-06-21 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transporteurs', '0024_auto_20180619_1813'),
    ]

    # Related to 0004
    operations = [
        migrations.RunSQL("""
            DROP INDEX transporteur_search_trgm;
        """),
        migrations.RunSQL("""
            CREATE INDEX transporteur_search_trgm_enseigne ON transporteur USING GIN (enseigne GIN_TRGM_OPS);
        """)
    ]
