# Generated by Django 2.0.6 on 2018-06-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporteurs', '0025_search_enseigne'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporteur',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
