version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.5.3
      - image: circleci/node:latest-browsers
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_DB: circleci_test
          POSTGRES_USER: circleci

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - pip-dependencies-{{ checksum "requirements_test.txt" }}
            - pip-dependencies-

      - restore_cache:
          keys:
            - npm-dependencies-{{ checksum "package.txt" }}
            - npm-dependencies-

      - run:
          name: install Python dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements_test.txt

      - save_cache:
          paths:
            - venv
          key: pip-dependencies-{{ checksum "requirements_test.txt" }}

      - run:
          name: install npm packages
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: npm-dependencies-{{ checksum "package.json" }}

      - run:
          name: install test settings
          command: |
            cp adock/settings_circleci.py adock/settings_local.py

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python manage.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports
