# Generated by Django 2.1.4 on 2018-12-20 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("accounts", "0001_initial")]

    operations = [
        migrations.RunSQL("DROP TABLE IF EXISTS auth_user_groups"),
        migrations.RunSQL("DROP TABLE IF EXISTS auth_user_user_permissions"),
        migrations.RunSQL("DROP TABLE IF EXISTS auth_user"),
    ]
