# Generated by Django 2.2 on 2019-04-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_subscribed_newsletter',
            field=models.BooleanField(default=False, help_text="Indique si l'utilisateur souhaite recevoir la lettre d'information.", verbose_name="Est abonné à la lettre d'information"),
        ),
    ]
