# Generated by Django 2.1.5 on 2019-01-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0002_remove_old_auth_user")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                default="foo@example.com",
                editable=False,
                max_length=255,
                unique=True,
                verbose_name="username",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, default="", max_length=255, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, default="", max_length=30, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="last name"
            ),
        ),
    ]
