# Generated by Django 2.1.7 on 2019-03-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190130_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_accepted_cgu',
            field=models.BooleanField(default=False, help_text="Chaque fois que les CGU sont modifiées, ce drapeau est remis à faux pour l'ensemble des utilisateurs.", verbose_name='A accepté les dernières CGU'),
        ),
    ]
