# Generated by Django 2.1.2 on 2018-10-25 09:42

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models
import phonenumber_field.modelfields

import adock.carriers.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carrier",
            fields=[
                (
                    "siret",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=14,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("raison_sociale", models.CharField(max_length=131)),
                ("enseigne", models.CharField(max_length=131)),
                ("enseigne_unaccent", models.CharField(max_length=131)),
                ("categorie_juridique", models.TextField()),
                ("is_siege", models.BooleanField(default=False)),
                ("adresse", models.CharField(max_length=126)),
                ("code_postal", models.CharField(max_length=5)),
                ("ville", models.CharField(max_length=32)),
                ("departement", models.CharField(blank=True, default="", max_length=3)),
                (
                    "telephone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, default="", max_length=128
                    ),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("email_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("date_creation", models.DateField(blank=True, null=True)),
                ("debut_activite", models.DateField(blank=True, null=True)),
                ("code_ape", models.CharField(max_length=5)),
                ("libelle_ape", models.CharField(max_length=65)),
                ("gestionnaire", models.CharField(max_length=131)),
                ("lti_numero", models.CharField(blank=True, default="", max_length=16)),
                ("lti_date_debut", models.DateField(blank=True, null=True)),
                ("lti_date_fin", models.DateField(blank=True, null=True)),
                ("lti_nombre", models.PositiveSmallIntegerField(default=0)),
                ("lc_numero", models.CharField(blank=True, default="", max_length=16)),
                ("lc_date_debut", models.DateField(blank=True, null=True)),
                ("lc_date_fin", models.DateField(blank=True, null=True)),
                ("lc_nombre", models.PositiveSmallIntegerField(default=0)),
                ("numero_tva", models.CharField(blank=True, max_length=13, null=True)),
                (
                    "working_area",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Non définie"),
                            ("INTERNATIONAL", "Internationale"),
                            ("FRANCE", "France"),
                            ("REGION", "Régionale"),
                            ("DEPARTEMENT", "Départementale"),
                        ],
                        default="",
                        max_length=15,
                    ),
                ),
                (
                    "working_area_departements",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=3),
                        blank=True,
                        null=True,
                        size=None,
                        validators=[
                            adock.carriers.validators.validate_french_departement
                        ],
                    ),
                ),
                (
                    "specialities",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("LOT", "Transport de lots"),
                                ("PALETTE", "Palettes / Messagerie palettisée"),
                                ("URBAIN", "Urbain / Dernier kilomètre"),
                                ("VRAC_SOLIDE", "Vrac solide"),
                                ("VRAC_LIQUIDE", "Vrac liquide"),
                                ("TEMPERATURE", "Température dirigée"),
                                ("PLATEAU", "Plateau bachés et spécifiques"),
                                ("MESSAGERIE", "Messagerie express"),
                                ("MULTIMODAL", "Multimodal"),
                                ("LOCATION", "Location"),
                                ("ANIMAL", "Animaux vivants"),
                                ("VEHICULE", "Transport de véhicules"),
                                ("AUTRE", "Autre"),
                            ],
                            max_length=63,
                        ),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("completeness", models.PositiveSmallIntegerField(default=40)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date de la supression de l'établissement du registre des transports.",
                        null=True,
                    ),
                ),
                (
                    "sirene_deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date de la suppression de l'établissement de la base Sirène.",
                        null=True,
                    ),
                ),
                ("edit_code", models.IntegerField(blank=True, null=True)),
                ("edit_code_at", models.DateTimeField(blank=True, null=True)),
                (
                    "objectif_co2",
                    models.CharField(
                        blank=True,
                        choices=[("ENLISTED", "Engagé"), ("LABELLED", "Labellisé")],
                        default="",
                        max_length=8,
                    ),
                ),
                ("objectif_co2_begin", models.DateField(blank=True, null=True)),
                ("objectif_co2_end", models.DateField(blank=True, null=True)),
            ],
            options={"db_table": "carrier"},
        ),
        migrations.CreateModel(
            name="CarrierFeed",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=32)),
                ("title", models.CharField(max_length=126)),
                ("url", models.URLField()),
                ("filename", models.FileField(upload_to="")),
                ("downloaded_at", models.DateTimeField(auto_now_add=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"db_table": "carrier_feed"},
        ),
        migrations.CreateModel(
            name="CarrierLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("data", django.contrib.postgres.fields.jsonb.JSONField()),
                (
                    "carrier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="carriers.Carrier",
                    ),
                ),
            ],
            options={"db_table": "carrier_log"},
        ),
    ]
