# Generated by Django 2.1.2 on 2018-10-25 10:02

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("carriers", "0001_initial")]

    operations = [TrigramExtension()]
