# Generated by Django 2.1.2 on 2018-10-25 10:04
from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("carriers", "0002_pg_trgm_extension")]

    operations = [UnaccentExtension()]
