# Generated by Django 2.1.2 on 2018-10-25 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("carriers", "0003_unaccent_extension")]

    operations = [
        migrations.RunSQL(
            """
            CREATE INDEX IF NOT EXISTS carrier_search_trgm_enseigne_unaccent
                ON carrier
                USING GIN (enseigne_unaccent GIN_TRGM_OPS);
            """
        )
    ]
