# Generated by Django 2.1.3 on 2018-11-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0004_index_enseigne_unaccent'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carrier',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='sirene_deleted_at',
            field=models.DateTimeField(blank=True, help_text="Date de la suppression de l'établissement de la base Sirene.", null=True),
        ),
    ]
