# Generated by Django 2.2 on 2019-04-17 10:15

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("carriers", "0006_auto_20190411_1340")]

    operations = [
        migrations.AddIndex(
            model_name="carrier",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["enseigne_unaccent"],
                name="carrier_trgm_enseigne_unaccent",
                opclasses=["gin_trgm_ops"],
            ),
        )
    ]
