# Generated by Django 2.2 on 2019-04-18 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("carriers", "0007_auto_20190417_1215")]

    operations = [
        migrations.RunSQL(
            """DROP INDEX IF EXISTS carrier_search_trgm_enseigne_unaccent"""
        )
    ]
