# Generated by Django 2.2.1 on 2019-06-27 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carriers', '0010_auto_20190521_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierRenewLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('lti_nombre', models.PositiveSmallIntegerField(default=0)),
                ('lc_nombre', models.PositiveSmallIntegerField(default=0)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carriers.Carrier')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrier_renew_licenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'carrier_renew_license',
            },
        ),
    ]
