# Generated by Django 2.1.7 on 2019-03-04 13:56

from django.db import migrations

FIELDS = [
    "telephone",
    "email",
    "working_area",
    "working_area_departements",
    "specialities",
    "website",
    "description",
]


def carrier_differences(carrier, json_values):
    differences = {}
    for field in FIELDS:
        json_value = json_values.get(field, "")
        column_value = getattr(carrier, field)

        if field == "telephone":
            column_value = str(column_value) if column_value else column_value
        elif field in ("working_area_departements", "specialities"):
            json_value = sorted(json_value) if json_value else json_value
            column_value = sorted(column_value) if column_value else column_value

        if column_value != json_value:
            differences[field] = column_value

    return differences


def create_carrier_log(CarrierLog, carrier, differences):
    carrier_log = CarrierLog.objects.create(
        carrier=carrier, created_at=carrier.validated_at, data=differences
    )
    # workaround to set the default value
    carrier_log.created_at = carrier.validated_at
    carrier_log.save()


def forwards_func(apps, schema_director):
    CarrierLog = apps.get_model("carriers", "CarrierLog")

    current_carrier = None
    count = 0
    for carrier_log in CarrierLog.objects.order_by("carrier_id", "id", "created_at"):
        if current_carrier != carrier_log.carrier:
            if current_carrier is not None:
                differences = carrier_differences(current_carrier, json_carrier_values)
                if differences:
                    count += 1
                    create_carrier_log(CarrierLog, current_carrier, differences)
            json_carrier_values = {}
            current_carrier = carrier_log.carrier

        json_carrier_values.update(carrier_log.data)

    print("Logs created: ", count)


class Migration(migrations.Migration):

    dependencies = [("carriers", "0010_carriereditable")]

    operations = [migrations.RunPython(forwards_func)]
