# Generated by Django 2.1.7 on 2019-03-04 21:21

from django.db import migrations


def forwards_func(apps, schema_director):
    CarrierLog = apps.get_model("carriers", "CarrierLog")
    CarrierEditable = apps.get_model("carriers", "CarrierEditable")
    current_carrier = None
    for carrier_log in CarrierLog.objects.order_by("carrier_id", "id", "created_at"):
        if carrier_log.carrier != current_carrier:
            current_carrier = carrier_log.carrier
            data = {}
            # Ignore the initial carrier log
        else:
            created_at = previous_carrier_log.created_at
            data.update(carrier_log.data)
            carrier_editable = CarrierEditable.objects.create(
                carrier=current_carrier,
                created_at=created_at,
                validated_at=created_at,
                created_by=None,
                telephone=data.get("telephone", ""),
                email=data.get("email", ""),
                # WORKING_AREA_UNDEFINED
                working_area=data.get("working_area", ""),
                working_area_departements=data.get("working_area_departements", []),
                specialities=data.get("specialities", []),
                website=data.get("website", ""),
                description=data.get("description", ""),
            )
            # Workaround auto_now_add
            carrier_editable.created_at = created_at
            carrier_editable.save()

        previous_carrier_log = carrier_log


class Migration(migrations.Migration):

    dependencies = [("carriers", "0011_add_final_carrier_log")]

    operations = [migrations.RunPython(forwards_func)]
