# Generated by Django 2.2.3 on 2019-09-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0012_remove_dots_from_enseigne_unaccent'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrierlicenserenewal',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
