# Generated by Django 2.2.3 on 2019-09-10 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("carriers", "0013_carrierlicenserenewal_delivered_at")]

    operations = [
        migrations.AlterField(
            model_name="carrierlicenserenewal",
            name="carrier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="license_renewals",
                to="carriers.Carrier",
            ),
        )
    ]
