# Generated by Django 2.2.5 on 2019-09-16 13:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("carriers", "0015_add_relations_carrier_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="carrier",
            name="users",
            field=models.ManyToManyField(
                related_name="carriers",
                through="carriers.CarrierUser",
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
