# Generated by Django 2.1.7 on 2019-03-06 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0016_auto_20190306_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrierlog',
            name='carrier',
        ),
        migrations.DeleteModel(
            name='CarrierLog',
        ),
    ]
