# Generated by Django 2.1.7 on 2019-03-06 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0017_auto_20190306_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrier',
            name='owners',
        ),
    ]
