# Generated by Django 2.1.7 on 2019-03-07 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("carriers", "0018_remove_carrier_owners")]

    operations = [
        migrations.RunSQL(
            """
with new_carrier_editable AS (
  insert into carrier_editable (
      carrier_id,
      telephone,
      email,
      created_at,
      confirmed_at,
      working_area,
      working_area_departements,
      specialities,
      website,
      description
    )
    select
      siret,
      '' as telephone,
      '' as email,
      now() as created_at,
      null as confirmed_at,
      'DEPARTEMENT' as working_area,
      -- Default departement for working area departements in company departement
      case when departement is null then null else array[departement] end as working_area_departements,
      null as specialities,
      '' as website,
      '' as description
    from carrier
    where carrier.editable_id is null
  returning *
) update carrier set editable_id = nce.id from new_carrier_editable nce where siret = nce.carrier_id;
"""
        )
    ]
